import { jobThaiRoles, jobThaiSnapshot, labourMarketRoles, labourMarketSnapshot, ploEvidence } from "../labourMarketData";
import { PageHead } from "./ui";

export default function LabourMarketBenchmark(){return <>
  <PageHead title="Labour Market Benchmark" subtitle={`หลักฐานตลาดงานด้านพืชจาก JobThai และ Jobsdb · อัปเดต ${jobThaiSnapshot.date}`}/>
  <section className="metric-grid"><div><strong>{jobThaiSnapshot.agricultureJobs}</strong><span>ประกาศในหมวดเกษตร JobThai</span></div><div><strong>{jobThaiSnapshot.examples}</strong><span>งานพืช JobThai ที่ตรวจรายละเอียด</span></div><div><strong>{labourMarketSnapshot.examples}</strong><span>ตัวอย่างเดิมจาก Jobsdb</span></div><div><strong>6</strong><span>PLO ที่ตลาดงานสนับสนุน</span></div></section>
  <p className="source-note">ข้อมูลเป็น snapshot ณ วันสำรวจ หมวดเกษตรของ JobThai รวมปศุสัตว์และประมง จึงคัดเฉพาะประกาศที่เกี่ยวข้องกับพืชศาสตร์แบบเจาะจง บางตำแหน่งกำหนดปริญญาตรี จึงใช้ภาระงานและทักษะเป็นหลักฐานออกแบบหลักสูตร ไม่ได้ใช้ยืนยันสิทธิสมัครงานของผู้จบ ปวส.</p>
  <section className="content-section"><h2>ประกาศด้านพืชจาก JobThai</h2><div className="course-list compact-list labour-list">{jobThaiRoles.map(([company,role,skills,url])=><article key={`${company}-${role}`}><code>JobThai</code><div><h2><a className="text-link" href={url} target="_blank" rel="noreferrer">{role}</a></h2><span>{company} · {skills}</span></div></article>)}</div></section>
  <section className="hero-panel"><p className="source-chip">JOBTHAI FINDING</p><h2>ตลาดต้องการคนที่เชื่อม “แปลงผลิต–ข้อมูล–มาตรฐาน–เกษตรกร–ตลาด”</h2><p>หลักฐานใหม่เน้นการวางแผนและติดตามแปลง การผลิตเมล็ดพันธุ์ Smart Farm และข้อมูลเซนเซอร์ การตรวจสอบย้อนกลับ GHPs/HACCP ตลอดจนการสื่อสารและพัฒนาตลาด ซึ่งสนับสนุน PLO1–PLO6 เดิมครบถ้วน</p></section>
  <section className="content-section"><h2>ชุดเปรียบเทียบเดิมจาก Jobsdb</h2><p className="source-note">สำรวจ {labourMarketSnapshot.date} · ตัวอย่างคัดเลือก {labourMarketSnapshot.examples} ตำแหน่ง</p><div className="course-list compact-list labour-list">{labourMarketRoles.map(([company,role,skills])=><article key={`${company}-${role}`}><code>{company}</code><div><h2>{role}</h2><span>{skills}</span></div></article>)}</div></section>
  <section className="content-section"><h2>ตลาดแรงงานยืนยัน PLO1–PLO6</h2><div className="outcome-list">{ploEvidence.map(([code,title,evidence])=><article key={code}><span>{code}</span><div><h3>{title}</h3><p>{evidence}</p></div></article>)}</div></section>
  <section className="hero-panel"><p className="source-chip">PLO ALIGNMENT</p><h2>หลักฐานตลาดแรงงานเชื่อมโยงกับ PLO1–PLO6</h2><p>Production + Technology/Data + Problem Solving + Business + Communication พร้อมมาตรฐานและความยั่งยืน ปรากฏในข้อมูลตลาดแรงงานและผลลัพธ์การเรียนรู้ของหลักสูตร</p></section>
</>}
